const TOKEN_VALIDATED = 'TOKEN_VALIDATED'
const USER_FETCHED_AUTH = 'USER_FETCHED_AUTH'
const SET_USER_TO_INITIAL_STATE = 'SET_USER_TO_INITIAL_STATE'
const SET_CURRENT_USER = 'SET_CURRENT_USER'

export {
  TOKEN_VALIDATED,
  USER_FETCHED_AUTH,
  SET_USER_TO_INITIAL_STATE,
  SET_CURRENT_USER,
}